# Generated by Django 5.1.4 on 2024-12-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='user',
            name='servicio',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Service'),
        ),
    ]
