# Generated by Django 5.1.4 on 2025-01-22 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0003_rename_direccion_paciente_localidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('via', models.CharField(choices=[('Oral', 'Oral'), ('Puff', 'Puff'), ('Endovenosa', 'Endovenosa'), ('Intramuscular', 'Intramuscular'), ('Subcutanea', 'Subcutanea'), ('Otro', 'Otro')], default='Oral', max_length=50)),
                ('dosis', models.CharField(max_length=50)),
                ('indicacion', models.CharField(choices=[('Cada 6 horas', 'Cada 6 horas'), ('Cada 8 horas', 'Cada 8 horas'), ('Cada 12 horas', 'Cada 12 horas'), ('Cada 24 horas', 'Cada 24 horas')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teleseguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
                ('condicion', models.CharField(choices=[(' Alta Medica', ' Alta Medica'), ('Internado', 'Internado'), ('Otro', 'Otro')], default='Alta Medica', max_length=100)),
                ('consentimiento_seguimiento', models.BooleanField(choices=[(True, 'Aceptado'), (False, 'Rechazado')], default=True)),
                ('estado', models.CharField(choices=[('Derivado', 'Derivado'), ('en_proceso', 'En Proceso'), ('realizado', 'Realizado'), ('no_realizado', 'No Realizado')], default='Derivado', max_length=20)),
                ('diagnostico', models.TextField(blank=True, max_length=1000, null=True)),
                ('medicaciones', models.ManyToManyField(blank=True, to='teleenfermeria.medicacion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(max_length=1000)),
                ('estado', models.CharField(choices=[('Derivado', 'Derivado'), ('realizado', 'Realizado'), ('no_realizado', 'No Realizado')], default='en_proceso', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teleseguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleenfermeria.teleseguimiento')),
            ],
        ),
    ]
