# Generated by Django 5.1.4 on 2025-01-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleenfermeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleseguimiento',
            name='consentimiento_seguimiento',
            field=models.CharField(choices=[('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('en_espera', 'En espera')], default='en_espera', max_length=100),
        ),
    ]
