# Generated by Django 5.1.4 on 2025-01-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleenfermeria', '0002_alter_teleseguimiento_consentimiento_seguimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='estado',
        ),
        migrations.AlterField(
            model_name='teleseguimiento',
            name='consentimiento_seguimiento',
            field=models.CharField(choices=[('aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('En espera', 'En espera')], default='en_espera', max_length=100),
        ),
    ]
