# Generated by Django 5.1.4 on 2025-01-26 22:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleenfermeria', '0003_remove_seguimiento_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicacion',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='medicacion',
            name='indicacion',
        ),
        migrations.AlterField(
            model_name='teleseguimiento',
            name='fecha_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='TeleseguimientoMedicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=50)),
                ('indicacion', models.CharField(choices=[('Cada 6 horas', 'Cada 6 horas'), ('Cada 8 horas', 'Cada 8 horas'), ('Cada 12 horas', 'Cada 12 horas'), ('Cada 24 horas', 'Cada 24 horas')], max_length=50)),
                ('medicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleenfermeria.medicacion')),
                ('teleseguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleenfermeria.teleseguimiento')),
            ],
        ),
    ]
