# Generated by Django 5.1.4 on 2025-01-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleenfermeria', '0004_remove_medicacion_dosis_remove_medicacion_indicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicacion',
            name='tipo',
            field=models.CharField(choices=[('Antibiotico', 'Antibiotico'), ('Antipiretico', 'Antipiretico'), ('Analgésico', 'Analgésico'), ('Antiinflamatorio', 'Antiinflamatorio'), ('Aerosol', 'Aerosol'), ('Corticosteroide', 'Corticosteroide')], default='otros', max_length=50),
        ),
    ]
