# Generated by Django 5.1.4 on 2025-01-26 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleenfermeria', '0005_medicacion_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicacion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='medicacion',
            name='via',
        ),
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=50)),
                ('via', models.CharField(choices=[('oral', 'Oral'), ('puff', 'Puff'), ('endovenosa', 'Endovenosa'), ('intramuscular', 'Intramuscular'), ('subcutanea', 'Subcutánea'), ('otro', 'Otro')], default='oral', max_length=50)),
                ('tipo', models.CharField(choices=[('antibiotico', 'Antibiótico'), ('antipiretico', 'Antipirético'), ('analgesico', 'Analgésico'), ('antiinflamatorio', 'Antiinflamatorio'), ('aerosol', 'Aerosol'), ('corticosteroide', 'Corticosteroide')], default='otro', max_length=50)),
                ('indicacion', models.CharField(choices=[('6h', 'Cada 6 horas'), ('8h', 'Cada 8 horas'), ('12h', 'Cada 12 horas'), ('24h', 'Cada 24 horas')], max_length=50)),
                ('medicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleenfermeria.medicacion')),
                ('teleseguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to='teleenfermeria.teleseguimiento')),
            ],
        ),
        migrations.DeleteModel(
            name='TeleseguimientoMedicacion',
        ),
    ]
