# Generated by Django 5.1.4 on 2025-01-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleenfermeria', '0008_solicitudturno_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleseguimiento',
            name='vacunas',
            field=models.CharField(choices=[('completo', 'Completo'), ('en_proceso', 'En_Proceso'), ('incompleto', 'incompleto')], default='En_proceso', max_length=28),
        ),
        migrations.AlterField(
            model_name='teleseguimiento',
            name='consentimiento_seguimiento',
            field=models.CharField(choices=[('aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('En espera', 'En espera'), ('pasivo', 'Pasivo')], default='en_espera', max_length=100),
        ),
    ]
