# Generated by Django 5.1.4 on 2025-01-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleenfermeria', '0009_teleseguimiento_vacunas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleseguimiento',
            name='vacunas',
            field=models.CharField(choices=[('completo', 'Completo'), ('en_proceso', 'En Proceso'), ('incompleto', 'incompleto')], default='En proceso', max_length=28),
        ),
    ]
