# Generated by Django 5.1.4 on 2025-01-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleenfermeria', '0010_alter_teleseguimiento_vacunas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teleseguimiento',
            name='vacunas',
        ),
    ]
