# Generated by Django 5.1.4 on 2025-02-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleenfermeria', '0012_teleseguimiento_vacunas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teleseguimiento',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='teleseguimiento',
            name='motivo_consulta',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Motivo de consulta'),
        ),
        migrations.AlterField(
            model_name='teleseguimiento',
            name='vacunas',
            field=models.CharField(choices=[('completo', 'Completo'), ('en_proceso', 'En Proceso'), ('incompleto', 'Incompleto')], default='En proceso', max_length=28),
        ),
    ]
