# Generated by Django 5.1.4 on 2025-02-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleenfermeria', '0012_teleseguimiento_vacunas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleseguimiento',
            name='vacunas',
            field=models.CharField(choices=[('completo', 'Completo'), ('en_proceso', 'En Proceso'), ('incompleto', 'Incompleto')], default='En proceso', max_length=28),
        ),
    ]
