# Generated by Django 5.1.4 on 2025-02-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teleenfermeria", "0014_remove_teleseguimiento_descripcion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudturno",
            name="imagen_orden",
            field=models.ImageField(blank=True, null=True, upload_to="ordenes/"),
        ),
    ]
