# Generated by Django 5.1.4 on 2025-02-07 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teleenfermeria", "0015_solicitudturno_imagen_orden"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teleseguimiento",
            name="agente",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"groups__name": "teleenfermeria"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
