# Generated by Django 5.1.4 on 2025-02-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleenfermeria', '0017_alter_teleseguimiento_agente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleseguimiento',
            name='condicion',
            field=models.CharField(choices=[(' Alta Medica', ' Alta Medica'), ('Alta Teleseguimiento', 'Alta Teleseguimiento'), ('Otro', 'Otro')], default='Alta Medica', max_length=100),
        ),
    ]
