# Generated by Django 5.1.4 on 2025-02-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleenfermeria', '0018_alter_teleseguimiento_condicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleseguimiento',
            name='condicion',
            field=models.CharField(choices=[(' Alta Medica', ' Alta Medica'), ('Alta Teleseguimiento', 'Alta Teleseguimiento'), ('Otro', 'Otro')], default='Otro', max_length=100),
        ),
        migrations.AlterField(
            model_name='teleseguimiento',
            name='consentimiento_seguimiento',
            field=models.CharField(choices=[('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('En espera', 'En espera'), ('Pasivo', 'Pasivo')], default='en_espera', max_length=100),
        ),
    ]
