# Generated by Django 5.1.4 on 2024-12-30 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('color_identificativo', models.CharField(max_length=7)),
                ('orden_visualizacion', models.IntegerField()),
                ('capacidad_total', models.IntegerField()),
                ('nivel_alerta_ocupacion', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('HABITACION', 'Habitación'), ('AREA', 'Área')], max_length=10)),
                ('capacidad', models.IntegerField()),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncamas.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('RESERVADA', 'Reservada'), ('EN_REFACCION', 'En Refacción'), ('FUERA_DE_SERVICIO', 'Fuera de Servicio')], max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultima_limpieza', models.DateTimeField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.paciente')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncamas.ubicacion')),
            ],
        ),
    ]
