# Generated by Django 5.1.4 on 2024-12-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncamas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cama',
            name='ultima_limpieza',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
