# Generated by Django 5.1.4 on 2025-01-02 19:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncamas', '0002_alter_cama_ultima_limpieza'),
        ('pacientes', '0003_rename_direccion_paciente_localidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cama',
            name='paciente',
        ),
        migrations.CreateModel(
            name='PacienteCama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_liberacion', models.DateTimeField(blank=True, null=True)),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncamas.cama')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
