# Generated by Django 5.1.4 on 2025-01-02 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncamas', '0003_remove_cama_paciente_pacientecama'),
        ('pacientes', '0003_rename_direccion_paciente_localidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientecama',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.paciente'),
        ),
    ]
