# Generated by Django 5.1.4 on 2025-01-20 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestioncamas", "0004_alter_pacientecama_paciente"),
        ("pacientes", "0003_rename_direccion_paciente_localidad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pacientecama",
            name="paciente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pacientes.paciente",
            ),
        ),
    ]
