# Generated by Django 5.1.4 on 2024-12-31 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_direccion_alter_paciente_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='direccion',
            new_name='localidad',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='email',
            new_name='obra_social',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='paciente',
            name='arm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='causa_externa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='dni_tutor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='domicilio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_egreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_pase',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='historia_clinica',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre_tutor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pases',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_egreso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
