# Generated by Django 5.1.4 on 2025-01-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_rename_direccion_paciente_localidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='telefono2',
            field=models.CharField(blank=True, default='-', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='obra_social',
            field=models.CharField(blank=True, default='sin Datos', max_length=100, null=True),
        ),
    ]
