# Generated by Django 5.1.4 on 2025-02-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0005_alter_paciente_dni"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="dni",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
