# Generated by Django 4.2.17 on 2024-12-29 18:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProtocolosDigitales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='clase',
            field=models.CharField(choices=[('Normativa General', 'Normativa General'), ('Protocolo de Control de Infecciones', 'Protocolo de Control de Infecciones'), ('Protocolos Generales', 'Protocolos Generales'), ('Protocolos de Servicio', 'Protocolos de Servicio'), ('Instructivo de Procedimiento', 'Instructivo de Procedimiento')], default=datetime.datetime(2024, 12, 29, 18, 53, 2, 89, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='codigo',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='nombre',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveBigIntegerField()),
                ('archivo_pdf', models.FileField(upload_to='documentos/')),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_implementacion', models.DateTimeField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='ProtocolosDigitales.documento')),
            ],
        ),
    ]
