# Generated by Django 5.1.4 on 2025-02-14 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestioncamas', '0005_alter_pacientecama_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAislamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Contacto', 'Contacto'), ('Respiratorio', 'Respiratorio'), ('Gotas', 'Gotas'), ('Aéreo', 'Aéreo')], default='Contacto', max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('imagen_ilustracion', models.ImageField(blank=True, null=True, upload_to='aislamientos/imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Aislamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('cama_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncamas.pacientecama')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aislamientos.tipoaislamiento')),
            ],
        ),
    ]
